#!/usr/bin/env python3
"""ACE-100 extended linter (Issue 4).

Settles the pattern rules beyond tools/check.sh: sentence word limits with the
canonical count over logical sentences (ACE 5.1, 6.1, 8.5-8.8), paragraph
sentence counts (ACE 6.6), modality (ACE 3.7), contractions (ACE 4.2), Latin
abbreviations (ACE 8.4), replacements-table words (ACE 1.3), the progressive
form (ACE 3.3), heading depth (ACE 14.3), kebab-case names (ACE 14.1),
document types and genres (ACE 12.1, 12.5), and exemption declarations
(ACE 13.7, 17.7).

It does NOT check: the function-word layer (needs part-of-speech reading),
voice, the perfect tenses, "-ing" verb forms beyond the progressive (ACE 3.4
is a rule about grammar, and grammar needs a reader), meaning,
one-name-per-item, or topic division. A clean run is necessary and not
sufficient.

It also reads the comments of source files (ACE 10.1). Layer L1 reaches every
comment, and layer L2 reaches the comments that end with terminal punctuation
(ACE 10.8). tools/README.md names the extensions that the sweep reads.

  tools/lint.py <path>...   # lint the given files
  tools/lint.py             # lint every governed file under the current tree

The full sweep honors .ace-ignore (comments and blank lines permitted), and a
finding is not reported when its rule identifier is in the document's `exempt`
property (ACE 13.7). A source file declares the same thing in an `ace-exempt`
comment (ACE 10.9).
"""
import re, sys, pathlib

ROOT = pathlib.Path.cwd()
TYPES = {'CollectionPage', 'TechArticle', 'HowTo', 'APIReference', 'DefinedTermSet'}
GENRES = {'decision-record', 'rules'}
# Predicate adjectives that follow "be" without a progressive reading
# ("the file is missing"). ING_NOT_VERB holds exact words whose letters end
# in "ing" with no verb suffix. The test is exact membership, and never a
# suffix test, so "using" and "processing" stay caught. Compounds of "thing"
# pass by suffix.
ING_ADJECTIVES = {'missing', 'existing', 'remaining', 'outstanding', 'pending', 'recurring', 'load-bearing'}
ING_NOT_VERB = {'thing', 'string', 'sing', 'king', 'ring', 'wing', 'spring', 'bring', 'during', 'sting', 'swing'}

# --- comments (Section 10) ---------------------------------------------------
# ACE 10.1 governs every comment. The sweep needs two facts about a source
# file. Does the kit read it, and how does that language spell a comment.
# Four families cover the list. An extension that is absent is not swept, and
# it is not compliant either. tools/README.md states the hole.
COMMENT_SYNTAX = {
    '.ts': 'c', '.tsx': 'c', '.js': 'c', '.jsx': 'c', '.mjs': 'c', '.cjs': 'c',
    '.go': 'c', '.rs': 'c', '.java': 'c', '.c': 'c', '.h': 'c', '.cpp': 'c',
    '.py': 'hash', '.sh': 'hash', '.bash': 'hash', '.rb': 'hash',
    '.yaml': 'hash', '.yml': 'hash', '.toml': 'hash',
    '.sql': 'sql',
    '.css': 'block', '.scss': 'block',
}
# The line token and the block delimiters of each family.
FAMILY = {
    'c':     ('//', '/*', '*/'),
    'hash':  ('#',  None, None),
    'sql':   ('--', '/*', '*/'),
    'block': (None, '/*', '*/'),
}
# ACE 10.6: a directive is structured data that a tool reads, not prose.
DIRECTIVE = re.compile(
    r'^\s*(eslint-|@ts-|biome-ignore|prettier-ignore|istanbul |c8 |v8 |'
    r'shellcheck |noqa|pylint:|mypy:|ruff:|type:|deno-lint|jshint |global |'
    r'@flow|#!|!/|nolint|codegen:|prettier:|oxlint-)', re.I)
# A rule of dashes or box characters divides sections of a comment. It is
# decoration, and it separates blocks the way a blank line does.
SEPARATOR = re.compile(r'[-=_~*─-╿]{4,}')
# ACE 10.4: the label of a generated file, in the first lines of the file.
GENERATED = re.compile(r'auto-?generated|generated by|do not edit', re.I)
# ACE 10.9: the source spelling of the `exempt` property (ACE 13.7).
ACE_EXEMPT = re.compile(r'^\s*ace-exempt:\s*(.*)$', re.I)
# A media type holds a slash and names no file.
MIME = re.compile(r'^(text|application|image|audio|video|multipart|font)/', re.I)
# A minified bundle is machine output with no label (ACE 10.4). One long line
# is the mark of it, and its "comments" are fragments of code.
MINIFIED = 1000

def split_fm(text):
    m = re.match(r'^---\n(.*?)\n---\n', text, re.S)
    return (m.group(1), text[m.end():]) if m else (None, text)

def load_banned():
    banned = []
    p = ROOT / 'docs/dictionary/replacements.md'
    if p.exists():
        for l in p.read_text().splitlines():
            if l.startswith('|') and not re.match(r'\|\s*-', l):
                left = l.strip('|').split('|')[0].strip()
                if left.lower() in ('not permitted', ''):
                    continue
                if '(' in left:  # context-dependent rows need a reader
                    continue
                for w in left.split(','):
                    w = w.strip().lower()
                    if w:
                        banned.append(w)
    return banned

def clean(body):
    t = re.sub(r'```.*?```', ' CODEBLOCK. ', body, flags=re.S)
    # A blockquote is the markdown spelling of a quotation (ACE 1.5).
    t = re.sub(r'^[ \t]*>.*$', ' QUOTE. ', t, flags=re.M)
    t = re.sub(r'`[^`]*`', ' TICK ', t)
    t = re.sub(r'"[^"\n]*"', ' QUOTE ', t)
    t = re.sub(r'\([^)]*\)', ' PAREN ', t)   # ACE 8.7: counts once, as one word
    t = re.sub(r'<[^>\n]*>', ' PLACEHOLDER ', t)
    t = re.sub(r'\]\(([^)]*)\)', '] ', t)
    return t

def extract_comments(text, family):
    """Return the comment lines of a source file, as (line number, text).

    The scan tracks string literals, because a URL inside a string holds the
    line token of the C family. A naive scan reads 80 such lines as comments
    in the field repository, and every one of them is a false finding.
    """
    line_tok, blk_open, blk_close = FAMILY[family]
    out, in_block, quote = [], False, ''
    for n, line in enumerate(text.splitlines(), 1):
        i, start = 0, None
        while i < len(line):
            if in_block:
                j = line.find(blk_close, i)
                if j < 0:
                    start = i if start is None else start
                    i = len(line)
                    break
                out.append((n, line[start if start is not None else i:j]))
                in_block, start, i = False, None, j + len(blk_close)
                continue
            ch = line[i]
            if quote:
                if ch == '\\':
                    i += 2
                    continue
                if ch == quote:
                    quote = ''
                i += 1
                continue
            if ch in '"\'`':
                quote = ch
                i += 1
                continue
            if line_tok and line.startswith(line_tok, i):
                # A shell reads "#" as a comment at the start of a word alone.
                # Parameter expansion holds it too: `${span%%#*}` is code, and
                # `${#files[@]}` is code. The word boundary tells them apart.
                if line_tok == '#' and i > 0 and line[i - 1] not in ' \t':
                    i += 1
                    continue
                out.append((n, line[i + len(line_tok):]))
                i = len(line)
                break
            if blk_open and line.startswith(blk_open, i):
                in_block, i = True, i + len(blk_open)
                start = i
                continue
            i += 1
        if in_block and start is not None:
            out.append((n, line[start:]))
            start = None
        # A quote never spans a line here. A template literal does, and the
        # cost of that simplification is a missed comment, never a false one.
        quote = ''
    # A block comment continues with a leading star, and JSDoc writes 2,752 of
    # them in the field repository. The star is punctuation, not prose.
    return [(n, re.sub(r'^\s*\*+ ?', '', t)) for n, t in out]

def comment_blocks(pieces):
    """Group the comment pieces into paragraphs, the way blank lines do."""
    blocks, cur, last = [], [], None
    for n, t in pieces:
        if DIRECTIVE.search(t) or ACE_EXEMPT.match(t):
            continue
        if not t.strip():
            if cur:
                blocks.append(cur)
            cur, last = [], n
            continue
        if SEPARATOR.search(t):
            if cur:
                blocks.append(cur)
            cur = []
            t = SEPARATOR.sub(' ', t)
            if re.search(r'[A-Za-z]', t):
                blocks.append([(n, t.strip())])
            last = n
            continue
        if last is not None and n > last + 1 and cur:
            blocks.append(cur)
            cur = []
        cur.append((n, t.strip()))
        last = n
    if cur:
        blocks.append(cur)
    return blocks

def check_source(rel, path, banned, note):
    """Apply the layers to the comments of one source file (ACE 10.1, 10.2)."""
    family = COMMENT_SYNTAX.get(path.suffix)
    if not family:
        return
    try:
        text = path.read_text()
    except (UnicodeDecodeError, OSError):
        return
    if any(len(l) > MINIFIED for l in text.splitlines()):
        return
    pieces = extract_comments(text, family)
    if not pieces:
        return
    # ACE 10.4: a label in the first comment lines exempts a generated file.
    head = ' '.join(t for _, t in pieces[:6])
    if GENERATED.search(head):
        return
    # ACE 10.9: the file-level declaration, with the obligations of ACE 17.7.
    exempt = ''
    for _, t in pieces:
        m = ACE_EXEMPT.match(t)
        if m:
            exempt += ' ' + m.group(1)
    if exempt.strip() and not (ROOT / 'docs/standard/deviations.md').exists():
        note(rel, 'ACE 17.7: ace-exempt declared but no deviations ledger exists')

    def cnote(n, msg):
        m = re.match(r'ACE ([0-9]+\.[0-9]+)', msg)
        if m and m.group(1) in exempt:
            return
        note(f'{rel}:{n}', msg)

    for block in comment_blocks(pieces):
        n0 = block[0][0]
        raw = ' '.join(t for _, t in block)
        # ACE 14.9: a backticked path in a comment resolves. Without that, a
        # division moved the file and left the pointer behind.
        # A comment holds shapes that a document rarely holds. Each one has a
        # slash and names no file: a package specifier, a route, an elided
        # path. ACE 14.9 reaches a repository path alone.
        for span in set(re.findall(r'`([^`]*)`', raw)):
            if '/' not in span or '<' in span or '*' in span or ' ' in span or '://' in span:
                continue
            if span[0] in '@/~…' or '…' in span or '..' in span:
                continue
            if MIME.match(span):
                continue
            p = span.split('#')[0].rstrip('/')
            if p and not (ROOT / p).exists() and not (path.parent / p).exists():
                cnote(n0, f'ACE 14.9: backticked path does not resolve: {span}')
        prose = clean(raw)

        # --- layer L1: every comment, sentence or fragment (ACE 10.1) -------
        if ';' in prose:
            cnote(n0, 'ACE 8.1: semicolon in prose')
        for pat, rule, msg in [
            (r'\be\.g\.|\bi\.e\.|\betc\.', '8.4', 'Latin abbreviation'),
            (r'\b(may|might|could|shall|should)\b', '3.7', 'modality word that is not permitted'),
            (r'\b(colour|behaviour|centre|licence|catalogue|organis|normalis|initialis|analys|recognis)[a-z]*',
             '1.12', 'British spelling'),
        ]:
            for mm in re.finditer(pat, prose, re.I):
                cnote(n0, f'ACE {rule}: {msg}: "{mm.group(0)}"')
        for w in banned:
            if re.search(r'\b' + re.escape(w) + r'\b', prose, re.I):
                cnote(n0, f'ACE 1.3: replacements-table word: "{w}"')
        for mm in re.finditer(r'\b(am|is|are|was|were|be|been|being)\s+([A-Za-z-]*[a-z]ing)\b', prose, re.I):
            w = mm.group(2).lower()
            if w in ING_ADJECTIVES or w in ING_NOT_VERB or w.endswith('thing'):
                continue
            cnote(n0, f'ACE 3.3: the progressive form: "{mm.group(1)} {mm.group(2)}"')

        # --- layer L2: the sentences alone (ACE 10.2, 10.8) -----------------
        # A unit that ends with terminal punctuation is a sentence. Other text
        # is a fragment, and layer L1 alone reached it above.
        units = re.split(r'(?<=[.!?])\s+(?=[A-Z0-9`"(*\[])', prose)
        sentences = [u for u in units if re.search(r'[.!?]["`\')\]]*\s*$', u)
                     and re.search(r'[A-Za-z]', u)]
        for s in sentences:
            toks = re.findall(r"[A-Za-z0-9][A-Za-z0-9'@-]*", s)
            if len(toks) > 20:
                cnote(n0, f'ACE 6.1: {len(toks)} words: {s.strip()[:70]}')
            for mm in re.finditer(r"\b\w+n't\b|\b\w+'re\b|\b\w+'ll\b|\b\w+'ve\b|\bit's\b", s, re.I):
                cnote(n0, f'ACE 4.2: contraction: "{mm.group(0)}"')
        if len(sentences) > 5:
            cnote(n0, f'ACE 6.6: {len(sentences)} sentences in one comment, the limit is five')

def sweep_files():
    files = sorted(ROOT.rglob('*.md'))
    files += sorted(f for f in ROOT.rglob('*') if f.suffix in COMMENT_SYNTAX and f.is_file())
    ign = ROOT / '.ace-ignore'
    if ign.exists():
        pats = [l.strip() for l in ign.read_text().splitlines()
                if l.strip() and not l.strip().startswith('#')]
        rx = [re.compile(p) for p in pats]
        files = [f for f in files
                 if not any(r.search(str(f.relative_to(ROOT))) for r in rx)]
    return files

def main(argv):
    banned = load_banned()
    files = [pathlib.Path(a) for a in argv] if argv else sweep_files()
    if not argv and not files:
        # A sweep that matches nothing is a broken sweep, not a clean one.
        print('the sweep matched no files — check .ace-ignore')
        return 2
    issues = []
    exempt_map = {}
    def note(f, msg):
        m = re.match(r'ACE ([0-9]+\.[0-9]+)', msg)
        if m and m.group(1) in exempt_map.get(str(f), ''):
            return
        issues.append(f"{f} — {msg}")

    for f in files:
        rel = f.relative_to(ROOT) if f.is_absolute() else f
        srel = str(rel)
        in_dict = srel.startswith('docs/dictionary')
        in_tmpl = srel.startswith('docs/templates')
        if f.suffix != '.md':
            check_source(rel, f, banned, note)
            continue
        text = f.read_text()
        fm, body = split_fm(text)
        if fm is None:
            note(rel, 'ACE 13.2: no front matter'); continue
        fmd = dict(re.findall(r'^"?(@?\w+)"?:\s*(.*)$', fm, re.M))
        exempt = fmd.get('exempt', '')
        exempt_map[str(rel)] = exempt
        def skipped(rule): return rule in exempt
        if exempt and not (ROOT / 'docs/standard/deviations.md').exists():
            note(rel, 'ACE 17.7: exempt declared but no deviations ledger exists')

        if fmd.get('@type') not in TYPES:
            note(rel, f"ACE 12.1: @type invalid: {fmd.get('@type')}")
        genre = fmd.get('genre', '')
        if genre and genre not in GENRES:
            note(rel, f"ACE 12.5: unknown genre: {genre}")
        if len(fmd.get('description', '').split()) > 20:
            note(rel, 'ACE 13.2: description over 20 words')

        if not re.fullmatch(r'(README|[a-z0-9]+(-[a-z0-9]+)*)\.md', f.name):
            note(rel, f'ACE 14.1: filename not kebab-case: {f.name}')
        for h in re.findall(r'^(#{4,6}) ', body, re.M):
            note(rel, f'ACE 14.3: heading depth {len(h)}')
        blines = body.strip('\n').split('\n')
        if len(blines) > 120 and not skipped('15.1'):
            note(rel, f'ACE 15.1: body {len(blines)} lines, the limit is 120')

        prose = clean(body)
        plines = prose.split('\n')
        prose_nt = '\n'.join(l for l in plines if not l.strip().startswith('|'))
        scope = prose_nt if in_dict else prose

        if ';' in scope:
            note(rel, 'ACE 8.1: semicolon in prose')
        for pat, rule, msg in [
            (r"\b\w+n't\b|\b\w+'re\b|\b\w+'ll\b|\b\w+'ve\b|\bit's\b", '4.2', 'contraction'),
            (r'\be\.g\.|\bi\.e\.|\betc\.', '8.4', 'Latin abbreviation'),
            (r'\b(may|might|could|shall|should)\b', '3.7', 'modality word that is not permitted'),
        ]:
            for mm in re.finditer(pat, scope, re.I):
                note(rel, f'ACE {rule}: {msg}: "{mm.group(0)}"')
        if genre not in ('decision-record',):
            for mm in re.finditer(r'\bwould\b', scope, re.I):
                note(rel, f'ACE 3.7: "would" outside a decision record — make sure that it is counterfactual (review, not error)')
                break
        if not in_dict:
            for w in banned:
                if re.search(r'\b' + re.escape(w) + r'\b', scope, re.I):
                    note(rel, f'ACE 1.3: replacements-table word: "{w}"')
        # The progressive form is the machine-settleable slice of the "-ing"
        # rules (ACE 3.3). The rest of ACE 3.4 is grammar, and needs a reader.
        for mm in re.finditer(r'\b(am|is|are|was|were|be|been|being)\s+([A-Za-z-]*[a-z]ing)\b', scope, re.I):
            w = mm.group(2).lower()
            if w in ING_ADJECTIVES or w in ING_NOT_VERB or w.endswith('thing'):
                continue
            note(rel, f'ACE 3.3: the progressive form: "{mm.group(1)} {mm.group(2)}"')

        limit = 15 if fmd.get('@type') == 'HowTo' else 20
        if in_tmpl:
            continue
        # Every count runs over the logical sentence (ACE 8.8). The wrapped
        # lines of one paragraph join before any split. A hard-wrapped
        # document counts the same as an unwrapped one.
        blocks, cur = [], []
        for l in plines:
            if l.strip():
                cur.append(l.strip())
            elif cur:
                blocks.append(cur); cur = []
        if cur:
            blocks.append(cur)
        for b in blocks:
            paras, items = [], []
            for l in b:
                if l.startswith('|') or l.startswith('#'):
                    continue
                m = re.match(r'^([-*]|\d+\.)\s+', l)
                if m:
                    items.append(l[m.end():])
                else:
                    paras.append(l)
            para = ' '.join(paras)
            for src in ([para] if para else []) + items:
                for s in re.split(r'[.!?]+', src.replace(':', '.')):
                    toks = re.findall(r"[A-Za-z0-9][A-Za-z0-9'@-]*", s)
                    if len(toks) > limit:
                        note(rel, f'ACE {"5.1" if limit==15 else "6.1"}: {len(toks)} words: {s.strip()[:70]}')
            # ACE 6.6: five sentences maximum in a paragraph. A vertical list
            # is its own structure (ACE 8.6), so the items stay outside the
            # count. The split here is deliberate. A period ends a sentence
            # only before a new start. So "ACE 8.5" and "changes.md" do not
            # divide, and a rule reference never inflates the count.
            if para:
                sents = [s for s in re.split(r'(?<=[.!?])\s+(?=[A-Z0-9`"(*\[])', para)
                         if re.search(r'[A-Za-z0-9]', s)]
                if len(sents) > 5:
                    note(rel, f'ACE 6.6: {len(sents)} sentences in one paragraph, the limit is five')

    for i in issues:
        print(i)
    if not issues:
        print(f'ok — {len(files)} file(s) pass the extended checks')
    return 1 if issues else 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
